Repository Neamar/KISS, pull requests merged in 2018-05, with the labels that each got.

#974 Fix onFling direction
  app/src/main/java/fr/neamar/kiss/forwarder/ExperienceTweaks.java
Labels: enhancement

#982 Tags menu / Folders
  app/src/main/java/fr/neamar/kiss/MainActivity.java
  app/src/main/java/fr/neamar/kiss/SettingsActivity.java
  app/src/main/java/fr/neamar/kiss/TagsHandler.java
  app/src/main/java/fr/neamar/kiss/forwarder/ForwarderManager.java
  app/src/main/java/fr/neamar/kiss/forwarder/TagsMenu.java
  app/src/main/java/fr/neamar/kiss/searcher/QuerySearcher.java
  app/src/main/java/fr/neamar/kiss/searcher/Searcher.java
  app/src/main/java/fr/neamar/kiss/searcher/TagsSearcher.java
  app/src/main/java/fr/neamar/kiss/ui/ListPopup.java
  app/src/main/res/layout/popup_divider.xml
  app/src/main/res/layout/popup_tag_menu.xml
  app/src/main/res/layout/popup_title.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: wip

#1001 Fix issue with dragging with only 1 favorite
  app/src/main/java/fr/neamar/kiss/forwarder/Favorites.java
Labels: bug
